package:
  name: kma
  version: 1.4.9

source:
  url: https://bitbucket.org/genomicepidemiology/kma/get/1.4.9.tar.gz

build:
  number: 0

requirements:
  build:
    - make
    - {{ compiler('c') }}
  host:
    - zlib
  run:
    - zlib

test:
  commands:
    - kma -h | grep KMA >/dev/null

about:
  home: https://bitbucket.org/genomicepidemiology/kma
  summary: 'KMA is mapping a method designed to map raw reads directly against redundant databases, in an ultra-fast manner using seed and extend.'
  license: Apache-2.0
extra:
  identifiers:
    - doi:10.1186/s12859-018-2336-6