on:
  workflow_dispatch

name: Create Release

jobs:
  auto-tag-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
  conda-osx:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false
      matrix:
        os: [ osx-latest ]

    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: Make conda yaml
        run: |
          pip install PyYAML
          python conda/make_conda.py

      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: envs/osx-build.yml

      - name: build conda package
        run: |
          conda install -c anaconda anaconda-client
          conda mambabuild conda -c conda-forge -c genomicepidemiology -c bioconda -c defaults --output-folder .

      - name: upload conda package
        run: |
          anaconda -t ${{ secrets.GENOMICEPIDEMIOLOGY_CONDA_AUTH_TOKEN }} upload --label main osx/*.tar.bz2

  conda-linux:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]

    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: Make conda yaml
        run: |
          pip install PyYAML
          python conda/make_conda.py

      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: envs/linux-build.yml

      - name: build conda package
        run: |
          conda install -c anaconda anaconda-client
          conda mambabuild conda -c conda-forge -c genomicepidemiology -c bioconda -c defaults --output-folder .

      - name: upload conda package
        run: |
          anaconda -t ${{ secrets.GENOMICEPIDEMIOLOGY_CONDA_AUTH_TOKEN }} upload --label main linux-64/*.tar.bz2